# 1. Load Data from all the stock csv files in directory

In [5]:
import datetime
import glob
import numpy as np
import pandas as pd

# Get CSV files list from a folder
csv_files = glob.glob("./TSLA-BID_ASK-*.csv")

# Read each CSV file into DataFrame
# This creates a list of dataframes
df_list = (pd.read_csv(file) for file in csv_files)

# Concatenate all DataFrames
df   = pd.concat(df_list, ignore_index=True)

## 1.1 Drop duplicates & check for missing values

In [14]:
dups = len(df['date'])-len(df['date'].drop_duplicates())
print("Before: # of duplicates", dups, ' out of ', len(df) , ' or ', round(dups/len(df),5), '%')

Before: # of duplicates 0  out of  1908010  or  0.0 %

In [11]:
# Drop duplicate entries
df.drop_duplicates(subset=['date'], keep='first', inplace=True)

In [13]:
# verify there are no duplicate values
df["date"].is_unique
dups = len(df['date'])-len(df['date'].drop_duplicates())
print("After: # of duplicates", dups, ' out of ', len(df) , ' or ', round(dups/len(df),5), '%')

After: # of duplicates 0  out of  1908010  or  0.0

(None, '%')

## 1.2 Print out all dates with confirming # of quotes (23400) and non-conforming number of quotes

In [15]:
df['date2_str']= df['date'][::].str.slice(stop=10)
pd_group_cnt = df.groupby(['date2_str'])['date2_str'].count().to_frame()
print("Confirming / correct number of quotes: 23,400")
print(pd_group_cnt.loc[pd_group_cnt['date2_str']==23400] )
pd.set_option('display.max_rows', None)
print("Dates Missing quotes")
print(pd_group_cnt.loc[pd_group_cnt['date2_str']!=23400] )
pd.set_option('display.max_rows', 10)
df = df.drop('date2_str', axis=1)

Confirming / correct number of quotes: 23,400
            date2_str
date2_str
2022-06-23      23400
2022-06-24      23400
2022-06-27      23400
2022-06-28      23400
2022-06-29      23400
...               ...
2022-10-11      23400
2022-10-12      23400
2022-10-13      23400
2022-10-14      23400
2022-10-17      23400

[81 rows x 1 columns]
Dates Missing quotes
            date2_str
date2_str
2022-06-22      12610

In [16]:
# Only want to track average to 3 decimal places.  Otherwise, end up with a lot of digits
df['average'] = df['average'].round(decimals = 3)

# 2.0 Describe data

In [17]:
df = df.sort_index(ascending=True)
#df = df.tail(10000)
#df = df.tail(30000)
df.describe()

,open,high,low,close,volume,average,barCount
count,1.908010e+06,1.908010e+06,1.908010e+06,1.908010e+06,1908010.0,1908010.0,1908010.0
mean,2.686557e+02,2.687600e+02,2.686341e+02,2.687381e+02,-1.0,-1.0,-1.0
std,2.991326e+01,2.991467e+01,2.991367e+01,2.991502e+01,0.0,0.0,0.0
min,2.041700e+02,2.042100e+02,2.041500e+02,2.041900e+02,-1.0,-1.0,-1.0
25%,2.401394e+02,2.402400e+02,2.401167e+02,2.402200e+02,-1.0,-1.0,-1.0
50%,2.755700e+02,2.756600e+02,2.755500e+02,2.756400e+02,-1.0,-1.0,-1.0
75%,2.950333e+02,2.951500e+02,2.950200e+02,2.951290e+02,-1.0,-1.0,-1.0
max,3.145250e+02,3.147100e+02,3.144167e+02,3.146263e+02,-1.0,-1.0,-1.0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1908010 entries, 0 to 1925999
Data columns (total 9 columns):
 #   Column     Dtype
---  ------     -----
 0   date       object
 1   open       float64
 2   high       float64
 3   low        float64
 4   close      float64
 5   volume     float64
 6   average    float64
 7   barCount   int64
 8   date2_str  object
dtypes: float64(6), int64(1), object(2)
memory usage: 145.6+ MB

# 3.0 Add computed columns

In [20]:
df.set_index('date')
df = df.sort_index()

In [21]:
# lambda functions

#return 1st value in series
def firstValue(rows):
    return rows.iloc[0]

#return last value in series
def lastValue(rows):
    return rows.iloc[-1]

#return arrow indicator for boxed in values;
#   -1 below lower bound
#    0 inside the box
#   +1 above the max value
def arrow(new_amt, old_amt, box):
    if old_amt == np.nan:
        return np.nan
    if new_amt == np.nan:
        return np.nan
    if (new_amt - old_amt) <= (box * -1):
        return '-1'
    if (new_amt - old_amt) >= box:
        return '1'
    else:
        return '0'

#  lambda function to adds up the last 5 values, excluding the very last value
def sum_last_5(rows):
    #print ("[" , rows[-6:-1], rows[-6:-1].sum(), "]")
    return rows[-6:-1].sum()

#  lambda function returns lowest of the last 5 values, excluding the very last value
def min_last_5(rows):
    return rows.iloc[-6:-1].min()

#  lambda function returns higest of  the last 5 values, excluding the very last value
def max_last_5(rows):
    return rows.iloc[-6:-1].max()

# Store/Save 1 second windows for h1, h2, h3, h4, h5

In [22]:
%%time
df['h1s_high_max'] = df['high'].rolling(window=2).agg( {'maxLast': firstValue})
df['h1s_low_min'] = df['low'].rolling(window=2).agg( {'minLast': firstValue})
df['h1s_barCount_sum'] = df['barCount'].rolling(window=2).agg( {'sumLast': firstValue})
df['h1s_volume_sum'] = df['volume'].rolling(window=2).agg( {'sumLast': firstValue})
df['h1s_average_avg'] = df['average'].rolling(window=2).agg( {'sumLast': firstValue})

In [23]:
%%time
df['h2s_high_max'] = df['high'].rolling(window=3).agg( {'maxLast': firstValue})
df['h2s_low_min'] = df['low'].rolling(window=3).agg( {'minLast': firstValue})
df['h2s_barCount_sum'] = df['barCount'].rolling(window=3).agg( {'sumLast': firstValue})
df['h2s_volume_sum'] = df['volume'].rolling(window=3).agg( {'sumLast': firstValue})
df['h2s_average_avg'] = df['average'].rolling(window=3).agg( {'sumLast': firstValue})

In [24]:
%%time
df['h3s_high_max'] = df['high'].rolling(window=4).agg( {'maxLast': firstValue})
df['h3s_low_min'] = df['low'].rolling(window=4).agg( {'minLast': firstValue})
df['h3s_barCount_sum'] = df['barCount'].rolling(window=4).agg( {'sumLast': firstValue})
df['h3s_volume_sum'] = df['volume'].rolling(window=4).agg( {'sumLast': firstValue})
df['h3s_average_avg'] = df['average'].rolling(window=4).agg( {'sumLast': firstValue})

In [25]:
%%time
df['h4s_high_max'] = df['high'].rolling(window=5).agg( {'maxLast': firstValue})
df['h4s_low_min'] = df['low'].rolling(window=5).agg( {'minLast': firstValue})
df['h4s_barCount_sum'] = df['barCount'].rolling(window=5).agg( {'sumLast': firstValue})
df['h4s_volume_sum'] = df['volume'].rolling(window=5).agg( {'sumLast': firstValue})
df['h4s_average_avg'] = df['average'].rolling(window=5).agg( {'sumLast': firstValue})

In [26]:
df = df.drop('date2_str', axis=1)

## Compute 5 second window summary

In [ ]:
%%time
df['h5s_high_max'] = df['high'].rolling(window=6).agg( {'maxLast5': max_last_5})
df['h5s_low_min'] = df['low'].rolling(window=6).agg( {'minLast5': min_last_5})
df['h5s_barCount_sum'] = df['barCount'].rolling(window=6).agg( {'sumLast5': sum_last_5})
df['h5s_volume_sum'] = df['volume'].rolling(window=6).agg( {'sumLast5': sum_last_5})
df['_h5s_weighted_vol_avg_sum'] = df['_weighted_vol_avg'].rolling(window=6).agg({'SumLast5': sum_last_5})

df['h5s_average_avg'] = df['_h5s_weighted_vol_avg_sum'] / df['h5s_volume_sum']
df['h5s_average_avg'] = df['h5s_average_avg'].round(decimals = 3)
df.drop(columns=['_h5s_weighted_vol_avg_sum'])
#

## Compute 10 second window summary

In [ ]:
%%time
df['h10s_high_max'] = df['high'].rolling(window=11).agg( {'maxLast5': max_last_5})
df['h10s_low_min'] = df['low'].rolling(window=11).agg( {'minLast5': min_last_5})
df['h10s_barCount_sum'] = df['barCount'].rolling(window=11).agg( {'sumLast5': sum_last_5})
df['h10s_volume_sum'] = df['volume'].rolling(window=11).agg( {'sumLast5': sum_last_5})
df['_h10s_weighted_vol_avg_sum'] = df['_weighted_vol_avg'].rolling(window=11).agg({'SumLast5': sum_last_5})

df['h10s_average_avg'] = df['_h10s_weighted_vol_avg_sum'] / df['h10s_volume_sum']
df['h10s_average_avg'] = df['h10s_average_avg'].round(decimals = 3)
df.drop(columns=['_h10s_weighted_vol_avg_sum'])

## Compute 15 second window summary

In [ ]:
%%time
df['h15s_high_max'] = df['high'].rolling(window=16).agg( {'maxLast5': max_last_5})
df['h15s_low_min'] = df['low'].rolling(window=16).agg( {'minLast5': min_last_5})
df['h15s_barCount_sum'] = df['barCount'].rolling(window=16).agg( {'sumLast5': sum_last_5})
df['h15s_volume_sum'] = df['volume'].rolling(window=16).agg( {'sumLast5': sum_last_5})
df['_h15s_weighted_vol_avg_sum'] = df['_weighted_vol_avg'].rolling(window=16).agg({'SumLast5': sum_last_5})

df['h15s_average_avg'] = df['_h15s_weighted_vol_avg_sum'] / df['h15s_volume_sum']
df['h15s_average_avg'] = df['h15s_average_avg'].round(decimals = 3)
df.drop(columns=['_h15s_weighted_vol_avg_sum'])

In [27]:
%%time
df = df.drop(columns=['_weighted_vol_avg'])

KeyError: "['_weighted_vol_avg'] not found in axis"

In [28]:
df.set_index('date')
df = df.sort_index(ascending=False)
df.reset_index()
df.head(100)

,date,open,high,low,close,volume,average,barCount,h1s_high_max,h1s_low_min,...,h3s_high_max,h3s_low_min,h3s_barCount_sum,h3s_volume_sum,h3s_average_avg,h4s_high_max,h4s_low_min,h4s_barCount_sum,h4s_volume_sum,h4s_average_avg
1925999,2022-08-02 15:29:50,303.1933,303.2933,303.1900,303.2900,-1.0,-1.0,-1,303.2933,303.1900,...,303.2933,303.2067,-1.0,-1.0,-1.0,303.2933,303.2433,-1.0,-1.0,-1.0
1925998,2022-08-02 15:29:49,303.1903,303.2933,303.1900,303.2933,-1.0,-1.0,-1,303.2933,303.2067,...,303.2933,303.2433,-1.0,-1.0,-1.0,303.2933,303.1367,-1.0,-1.0,-1.0
1925997,2022-08-02 15:29:48,303.2330,303.2933,303.2067,303.2900,-1.0,-1.0,-1,303.2933,303.2067,...,303.2933,303.1367,-1.0,-1.0,-1.0,303.2500,303.1367,-1.0,-1.0,-1.0
1925996,2022-08-02 15:29:47,303.2300,303.2933,303.2067,303.2933,-1.0,-1.0,-1,303.2933,303.2433,...,303.2500,303.1367,-1.0,-1.0,-1.0,303.2500,303.1367,-1.0,-1.0,-1.0
1925995,2022-08-02 15:29:46,303.2433,303.2933,303.2433,303.2933,-1.0,-1.0,-1,303.2933,303.1367,...,303.2500,303.1367,-1.0,-1.0,-1.0,303.2500,303.0767,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1925904,2022-08-02 15:28:15,302.8063,302.9067,302.7733,302.9000,-1.0,-1.0,-1,302.9100,302.7667,...,302.9900,302.7700,-1.0,-1.0,-1.0,302.9933,302.8867,-1.0,-1.0,-1.0
1925903,2022-08-02 15:28:14,302.7733,302.9100,302.7667,302.8897,-1.0,-1.0,-1,302.9167,302.8333,...,302.9933,302.8867,-1.0,-1.0,-1.0,303.0000,302.8867,-1.0,-1.0,-1.0
1925902,2022-08-02 15:28:13,302.8333,302.9167,302.8333,302.9100,-1.0,-1.0,-1,302.9900,302.7700,...,303.0000,302.8867,-1.0,-1.0,-1.0,303.0000,302.8867,-1.0,-1.0,-1.0
1925901,2022-08-02 15:28:12,302.8323,302.9900,302.7700,302.8937,-1.0,-1.0,-1,302.9933,302.8867,...,303.0000,302.8867,-1.0,-1.0,-1.0,303.0000,302.9133,-1.0,-1.0,-1.0
1925900,2022-08-02 15:28:11,302.8867,302.9933,302.8867,302.9900,-1.0,-1.0,-1,303.0000,302.8867,...,303.0000,302.9133,-1.0,-1.0,-1.0,303.0500,302.9600,-1.0,-1.0,-1.0

## Compute Future 5 second window summary

In [29]:
%%time
df['f5s_average'] = df['average'].rolling(window=6).agg( {'firstValue': firstValue})
df.head(100)

,date,open,high,low,close,volume,average,barCount,h1s_high_max,h1s_low_min,...,h3s_low_min,h3s_barCount_sum,h3s_volume_sum,h3s_average_avg,h4s_high_max,h4s_low_min,h4s_barCount_sum,h4s_volume_sum,h4s_average_avg,f5s_average
1925999,2022-08-02 15:29:50,303.1933,303.2933,303.1900,303.2900,-1.0,-1.0,-1,303.2933,303.1900,...,303.2067,-1.0,-1.0,-1.0,303.2933,303.2433,-1.0,-1.0,-1.0,NaN
1925998,2022-08-02 15:29:49,303.1903,303.2933,303.1900,303.2933,-1.0,-1.0,-1,303.2933,303.2067,...,303.2433,-1.0,-1.0,-1.0,303.2933,303.1367,-1.0,-1.0,-1.0,NaN
1925997,2022-08-02 15:29:48,303.2330,303.2933,303.2067,303.2900,-1.0,-1.0,-1,303.2933,303.2067,...,303.1367,-1.0,-1.0,-1.0,303.2500,303.1367,-1.0,-1.0,-1.0,NaN
1925996,2022-08-02 15:29:47,303.2300,303.2933,303.2067,303.2933,-1.0,-1.0,-1,303.2933,303.2433,...,303.1367,-1.0,-1.0,-1.0,303.2500,303.1367,-1.0,-1.0,-1.0,NaN
1925995,2022-08-02 15:29:46,303.2433,303.2933,303.2433,303.2933,-1.0,-1.0,-1,303.2933,303.1367,...,303.1367,-1.0,-1.0,-1.0,303.2500,303.0767,-1.0,-1.0,-1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1925904,2022-08-02 15:28:15,302.8063,302.9067,302.7733,302.9000,-1.0,-1.0,-1,302.9100,302.7667,...,302.7700,-1.0,-1.0,-1.0,302.9933,302.8867,-1.0,-1.0,-1.0,-1.0
1925903,2022-08-02 15:28:14,302.7733,302.9100,302.7667,302.8897,-1.0,-1.0,-1,302.9167,302.8333,...,302.8867,-1.0,-1.0,-1.0,303.0000,302.8867,-1.0,-1.0,-1.0,-1.0
1925902,2022-08-02 15:28:13,302.8333,302.9167,302.8333,302.9100,-1.0,-1.0,-1,302.9900,302.7700,...,302.8867,-1.0,-1.0,-1.0,303.0000,302.8867,-1.0,-1.0,-1.0,-1.0
1925901,2022-08-02 15:28:12,302.8323,302.9900,302.7700,302.8937,-1.0,-1.0,-1,302.9933,302.8867,...,302.8867,-1.0,-1.0,-1.0,303.0000,302.9133,-1.0,-1.0,-1.0,-1.0
1925900,2022-08-02 15:28:11,302.8867,302.9933,302.8867,302.9900,-1.0,-1.0,-1,303.0000,302.8867,...,302.9133,-1.0,-1.0,-1.0,303.0500,302.9600,-1.0,-1.0,-1.0,-1.0

In [30]:
df = df.sort_index(ascending=True)
df.reset_index()
df.head(100)

,date,open,high,low,close,volume,average,barCount,h1s_high_max,h1s_low_min,...,h3s_low_min,h3s_barCount_sum,h3s_volume_sum,h3s_average_avg,h4s_high_max,h4s_low_min,h4s_barCount_sum,h4s_volume_sum,h4s_average_avg,f5s_average
0,2022-08-25 12:29:54,293.780,293.81,293.78,293.810,-1.0,-1.0,-1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
1,2022-08-25 12:29:55,293.790,293.89,293.76,293.889,-1.0,-1.0,-1,293.81,293.78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
2,2022-08-25 12:29:56,293.791,293.98,293.79,293.960,-1.0,-1.0,-1,293.89,293.76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0
3,2022-08-25 12:29:57,293.839,293.96,293.79,293.960,-1.0,-1.0,-1,293.98,293.79,...,293.78,-1.0,-1.0,-1.0,NaN,NaN,NaN,NaN,NaN,-1.0
4,2022-08-25 12:29:58,293.919,293.96,293.84,293.960,-1.0,-1.0,-1,293.96,293.79,...,293.76,-1.0,-1.0,-1.0,293.81,293.78,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-08-25 12:31:29,293.490,293.55,293.49,293.550,-1.0,-1.0,-1,293.55,293.49,...,293.58,-1.0,-1.0,-1.0,293.71,293.57,-1.0,-1.0,-1.0,-1.0
96,2022-08-25 12:31:30,293.469,293.57,293.42,293.569,-1.0,-1.0,-1,293.55,293.49,...,293.50,-1.0,-1.0,-1.0,293.71,293.58,-1.0,-1.0,-1.0,-1.0
97,2022-08-25 12:31:31,293.509,293.65,293.47,293.609,-1.0,-1.0,-1,293.57,293.42,...,293.49,-1.0,-1.0,-1.0,293.65,293.50,-1.0,-1.0,-1.0,-1.0
98,2022-08-25 12:31:32,293.559,293.61,293.51,293.610,-1.0,-1.0,-1,293.65,293.47,...,293.49,-1.0,-1.0,-1.0,293.55,293.49,-1.0,-1.0,-1.0,-1.0
99,2022-08-25 12:31:33,293.540,293.61,293.54,293.610,-1.0,-1.0,-1,293.61,293.51,...,293.42,-1.0,-1.0,-1.0,293.55,293.49,-1.0,-1.0,-1.0,-1.0

In [31]:
%%time
pd.set_option('display.max_rows', 100)

df['f5s_10c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.10), axis=1)
df['f5s_15c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.15), axis=1)
df['f5s_20c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.20), axis=1)
df['f5s_25c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.25), axis=1)
df['f5s_30c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.30), axis=1)

CPU times: user 1min 7s, sys: 2.95 s, total: 1min 10s
Wall time: 1min 10s

In [34]:
df.head(100)

CPU times: user 70 µs, sys: 0 ns, total: 70 µs
Wall time: 71.8 µs

,date,open,high,low,close,volume,average,barCount,h1s_high_max,h1s_low_min,...,h4s_low_min,h4s_barCount_sum,h4s_volume_sum,h4s_average_avg,f5s_average,f5s_10c_arrow,f5s_15c_arrow,f5s_20c_arrow,f5s_25c_arrow,f5s_30c_arrow
0,2022-08-25 12:29:54,293.780,293.81,293.78,293.810,-1.0,-1.0,-1,NaN,NaN,...,NaN,NaN,NaN,NaN,-1.0,0,0,0,0,0
1,2022-08-25 12:29:55,293.790,293.89,293.76,293.889,-1.0,-1.0,-1,293.81,293.78,...,NaN,NaN,NaN,NaN,-1.0,0,0,0,0,0
2,2022-08-25 12:29:56,293.791,293.98,293.79,293.960,-1.0,-1.0,-1,293.89,293.76,...,NaN,NaN,NaN,NaN,-1.0,0,0,0,0,0
3,2022-08-25 12:29:57,293.839,293.96,293.79,293.960,-1.0,-1.0,-1,293.98,293.79,...,NaN,NaN,NaN,NaN,-1.0,0,0,0,0,0
4,2022-08-25 12:29:58,293.919,293.96,293.84,293.960,-1.0,-1.0,-1,293.96,293.79,...,293.78,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
5,2022-08-25 12:29:59,293.840,293.96,293.84,293.960,-1.0,-1.0,-1,293.96,293.84,...,293.76,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
6,2022-08-25 12:30:00,293.850,293.96,293.84,293.950,-1.0,-1.0,-1,293.96,293.84,...,293.79,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
7,2022-08-25 12:30:01,293.850,293.95,293.85,293.950,-1.0,-1.0,-1,293.96,293.84,...,293.79,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
8,2022-08-25 12:30:02,293.860,293.95,293.85,293.950,-1.0,-1.0,-1,293.95,293.85,...,293.84,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
9,2022-08-25 12:30:03,293.791,293.95,293.79,293.910,-1.0,-1.0,-1,293.95,293.85,...,293.84,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
10,2022-08-25 12:30:04,293.800,293.94,293.79,293.930,-1.0,-1.0,-1,293.95,293.79,...,293.84,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
11,2022-08-25 12:30:05,293.800,293.93,293.80,293.930,-1.0,-1.0,-1,293.94,293.79,...,293.85,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
12,2022-08-25 12:30:06,293.820,293.93,293.80,293.900,-1.0,-1.0,-1,293.93,293.80,...,293.85,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
13,2022-08-25 12:30:07,293.800,293.93,293.80,293.900,-1.0,-1.0,-1,293.93,293.80,...,293.79,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
14,2022-08-25 12:30:08,293.800,293.90,293.80,293.900,-1.0,-1.0,-1,293.93,293.80,...,293.79,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
15,2022-08-25 12:30:09,293.731,293.90,293.73,293.811,-1.0,-1.0,-1,293.90,293.80,...,293.80,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
16,2022-08-25 12:30:10,293.661,293.86,293.65,293.723,-1.0,-1.0,-1,293.90,293.73,...,293.80,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
17,2022-08-25 12:30:11,293.660,293.80,293.66,293.799,-1.0,-1.0,-1,293.86,293.65,...,293.80,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
18,2022-08-25 12:30:12,293.660,293.80,293.66,293.720,-1.0,-1.0,-1,293.80,293.66,...,293.80,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
19,2022-08-25 12:30:13,293.660,293.72,293.66,293.720,-1.0,-1.0,-1,293.80,293.66,...,293.73,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
20,2022-08-25 12:30:14,293.660,293.72,293.66,293.720,-1.0,-1.0,-1,293.72,293.66,...,293.65,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
21,2022-08-25 12:30:15,293.610,293.72,293.61,293.710,-1.0,-1.0,-1,293.72,293.66,...,293.66,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
22,2022-08-25 12:30:16,293.600,293.71,293.60,293.670,-1.0,-1.0,-1,293.72,293.61,...,293.66,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
23,2022-08-25 12:30:17,293.465,293.67,293.46,293.535,-1.0,-1.0,-1,293.71,293.60,...,293.66,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
24,2022-08-25 12:30:18,293.461,293.64,293.46,293.578,-1.0,-1.0,-1,293.67,293.46,...,293.66,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
25,2022-08-25 12:30:19,293.470,293.58,293.46,293.580,-1.0,-1.0,-1,293.64,293.46,...,293.61,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
26,2022-08-25 12:30:20,293.450,293.58,293.45,293.500,-1.0,-1.0,-1,293.58,293.46,...,293.60,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
27,2022-08-25 12:30:21,293.449,293.68,293.40,293.579,-1.0,-1.0,-1,293.58,293.45,...,293.46,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
28,2022-08-25 12:30:22,293.449,293.58,293.40,293.579,-1.0,-1.0,-1,293.68,293.40,...,293.46,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
29,2022-08-25 12:30:23,293.499,293.68,293.45,293.669,-1.0,-1.0,-1,293.58,293.40,...,293.46,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
30,2022-08-25 12:30:24,293.529,293.68,293.46,293.679,-1.0,-1.0,-1,293.68,293.45,...,293.45,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
31,2022-08-25 12:30:25,293.539,293.68,293.51,293.631,-1.0,-1.0,-1,293.68,293.46,...,293.40,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
32,2022-08-25 12:30:26,293.510,293.63,293.51,293.581,-1.0,-1.0,-1,293.68,293.51,...,293.40,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
33,2022-08-25 12:30:27,293.450,293.58,293.40,293.530,-1.0,-1.0,-1,293.63,293.51,...,293.45,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
34,2022-08-25 12:30:28,293.421,293.53,293.42,293.520,-1.0,-1.0,-1,293.58,293.40,...,293.46,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
35,2022-08-25 12:30:29,293.450,293.53,293.42,293.530,-1.0,-1.0,-1,293.53,293.42,...,293.51,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
36,2022-08-25 12:30:30,293.450,293.53,293.45,293.530,-1.0,-1.0,-1,293.53,293.42,...,293.51,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
37,2022-08-25 12:30:31,293.450,293.53,293.45,293.530,-1.0,-1.0,-1,293.53,293.45,...,293.40,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
38,2022-08-25 12:30:32,293.510,293.68,293.45,293.660,-1.0,-1.0,-1,293.53,293.45,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
39,2022-08-25 12:30:33,293.510,293.66,293.51,293.650,-1.0,-1.0,-1,293.68,293.45,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
40,2022-08-25 12:30:34,293.510,293.66,293.51,293.659,-1.0,-1.0,-1,293.66,293.51,...,293.45,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
41,2022-08-25 12:30:35,293.450,293.66,293.43,293.580,-1.0,-1.0,-1,293.66,293.51,...,293.45,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
42,2022-08-25 12:30:36,293.430,293.64,293.43,293.481,-1.0,-1.0,-1,293.66,293.43,...,293.45,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
43,2022-08-25 12:30:37,293.400,293.50,293.39,293.499,-1.0,-1.0,-1,293.64,293.43,...,293.51,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
44,2022-08-25 12:30:38,293.422,293.66,293.40,293.637,-1.0,-1.0,-1,293.50,293.39,...,293.51,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
45,2022-08-25 12:30:39,293.420,293.64,293.42,293.620,-1.0,-1.0,-1,293.66,293.40,...,293.43,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
46,2022-08-25 12:30:40,293.449,293.62,293.42,293.580,-1.0,-1.0,-1,293.64,293.42,...,293.43,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
47,2022-08-25 12:30:41,293.440,293.58,293.43,293.550,-1.0,-1.0,-1,293.62,293.42,...,293.39,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
48,2022-08-25 12:30:42,293.440,293.55,293.44,293.550,-1.0,-1.0,-1,293.58,293.43,...,293.40,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
49,2022-08-25 12:30:43,293.519,293.65,293.44,293.629,-1.0,-1.0,-1,293.55,293.44,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
50,2022-08-25 12:30:44,293.520,293.63,293.52,293.620,-1.0,-1.0,-1,293.65,293.44,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
51,2022-08-25 12:30:45,293.500,293.62,293.49,293.570,-1.0,-1.0,-1,293.63,293.52,...,293.43,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
52,2022-08-25 12:30:46,293.500,293.57,293.50,293.570,-1.0,-1.0,-1,293.62,293.49,...,293.44,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
53,2022-08-25 12:30:47,293.382,293.57,293.38,293.511,-1.0,-1.0,-1,293.57,293.50,...,293.44,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
54,2022-08-25 12:30:48,293.380,293.51,293.38,293.460,-1.0,-1.0,-1,293.57,293.38,...,293.52,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
55,2022-08-25 12:30:49,293.380,293.46,293.38,293.460,-1.0,-1.0,-1,293.51,293.38,...,293.49,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
56,2022-08-25 12:30:50,293.410,293.46,293.38,293.460,-1.0,-1.0,-1,293.46,293.38,...,293.50,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
57,2022-08-25 12:30:51,293.410,293.46,293.41,293.460,-1.0,-1.0,-1,293.46,293.38,...,293.38,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
58,2022-08-25 12:30:52,293.321,293.46,293.32,293.410,-1.0,-1.0,-1,293.46,293.41,...,293.38,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
59,2022-08-25 12:30:53,293.330,293.56,293.32,293.470,-1.0,-1.0,-1,293.46,293.32,...,293.38,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
60,2022-08-25 12:30:54,293.369,293.48,293.33,293.480,-1.0,-1.0,-1,293.56,293.32,...,293.38,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
61,2022-08-25 12:30:55,293.350,293.48,293.35,293.480,-1.0,-1.0,-1,293.48,293.33,...,293.41,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
62,2022-08-25 12:30:56,293.350,293.48,293.35,293.480,-1.0,-1.0,-1,293.48,293.35,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
63,2022-08-25 12:30:57,293.370,293.56,293.32,293.558,-1.0,-1.0,-1,293.48,293.35,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
64,2022-08-25 12:30:58,293.409,293.56,293.32,293.549,-1.0,-1.0,-1,293.56,293.32,...,293.33,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
65,2022-08-25 12:30:59,293.371,293.56,293.32,293.492,-1.0,-1.0,-1,293.56,293.32,...,293.35,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
66,2022-08-25 12:31:00,293.350,293.49,293.32,293.479,-1.0,-1.0,-1,293.56,293.32,...,293.35,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
67,2022-08-25 12:31:01,293.330,293.49,293.33,293.430,-1.0,-1.0,-1,293.49,293.32,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
68,2022-08-25 12:31:02,293.330,293.43,293.33,293.430,-1.0,-1.0,-1,293.49,293.33,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
69,2022-08-25 12:31:03,293.350,293.48,293.33,293.430,-1.0,-1.0,-1,293.43,293.33,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
70,2022-08-25 12:31:04,293.350,293.43,293.35,293.420,-1.0,-1.0,-1,293.48,293.33,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
71,2022-08-25 12:31:05,293.321,293.42,293.32,293.410,-1.0,-1.0,-1,293.43,293.35,...,293.33,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
72,2022-08-25 12:31:06,293.320,293.41,293.32,293.410,-1.0,-1.0,-1,293.42,293.32,...,293.33,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
73,2022-08-25 12:31:07,293.330,293.41,293.32,293.410,-1.0,-1.0,-1,293.41,293.32,...,293.33,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
74,2022-08-25 12:31:08,293.340,293.42,293.32,293.420,-1.0,-1.0,-1,293.41,293.32,...,293.35,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
75,2022-08-25 12:31:09,293.330,293.43,293.32,293.420,-1.0,-1.0,-1,293.42,293.32,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
76,2022-08-25 12:31:10,293.389,293.49,293.33,293.489,-1.0,-1.0,-1,293.43,293.32,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
77,2022-08-25 12:31:11,293.390,293.49,293.35,293.490,-1.0,-1.0,-1,293.49,293.33,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
78,2022-08-25 12:31:12,293.420,293.49,293.39,293.490,-1.0,-1.0,-1,293.49,293.35,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
79,2022-08-25 12:31:13,293.420,293.49,293.42,293.490,-1.0,-1.0,-1,293.49,293.39,...,293.32,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
80,2022-08-25 12:31:14,293.420,293.49,293.42,293.490,-1.0,-1.0,-1,293.49,293.42,...,293.33,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
81,2022-08-25 12:31:15,293.459,293.53,293.42,293.529,-1.0,-1.0,-1,293.49,293.42,...,293.35,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
82,2022-08-25 12:31:16,293.470,293.53,293.46,293.520,-1.0,-1.0,-1,293.53,293.42,...,293.39,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
83,2022-08-25 12:31:17,293.460,293.53,293.42,293.530,-1.0,-1.0,-1,293.53,293.46,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
84,2022-08-25 12:31:18,293.460,293.53,293.42,293.530,-1.0,-1.0,-1,293.53,293.42,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
85,2022-08-25 12:31:19,293.420,293.53,293.42,293.500,-1.0,-1.0,-1,293.53,293.42,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
86,2022-08-25 12:31:20,293.517,293.62,293.42,293.617,-1.0,-1.0,-1,293.53,293.42,...,293.46,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
87,2022-08-25 12:31:21,293.520,293.62,293.52,293.620,-1.0,-1.0,-1,293.62,293.42,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
88,2022-08-25 12:31:22,293.520,293.62,293.52,293.620,-1.0,-1.0,-1,293.62,293.52,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
89,2022-08-25 12:31:23,293.520,293.62,293.52,293.620,-1.0,-1.0,-1,293.62,293.52,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
90,2022-08-25 12:31:24,293.570,293.71,293.52,293.709,-1.0,-1.0,-1,293.62,293.52,...,293.42,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
91,2022-08-25 12:31:25,293.580,293.71,293.57,293.700,-1.0,-1.0,-1,293.71,293.52,...,293.52,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
92,2022-08-25 12:31:26,293.580,293.71,293.58,293.650,-1.0,-1.0,-1,293.71,293.57,...,293.52,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
93,2022-08-25 12:31:27,293.500,293.65,293.50,293.551,-1.0,-1.0,-1,293.71,293.58,...,293.52,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
94,2022-08-25 12:31:28,293.490,293.55,293.49,293.550,-1.0,-1.0,-1,293.65,293.50,...,293.52,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
95,2022-08-25 12:31:29,293.490,293.55,293.49,293.550,-1.0,-1.0,-1,293.55,293.49,...,293.57,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
96,2022-08-25 12:31:30,293.469,293.57,293.42,293.569,-1.0,-1.0,-1,293.55,293.49,...,293.58,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
97,2022-08-25 12:31:31,293.509,293.65,293.47,293.609,-1.0,-1.0,-1,293.57,293.42,...,293.50,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
98,2022-08-25 12:31:32,293.559,293.61,293.51,293.610,-1.0,-1.0,-1,293.65,293.47,...,293.49,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
99,2022-08-25 12:31:33,293.540,293.61,293.54,293.610,-1.0,-1.0,-1,293.61,293.51,...,293.49,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0

In [33]:
df.to_csv("./TSLA-BID_ASK.csv", index=False)